### ISSUE TITLE
SUMMARY

### ISSUE THREAD

**Issue by franfranfranfran** [jane548/tea_cozy#6]
**GRADE**: Meets Expectations

**SUMMARY**: Good work on this project. The site looks great and you did an excellent job keeping both the project folder and the code neat, organized, and readable. Excellent work making use of flex display to help align items throughout the page as well.

Behind the scenes, try to always be on the lookout for ways to make your code more efficient. Leave out any extra, unused classes and look for opportunities to avoid repeated styling. You're off to a great start with this using general classes like 'location' and 'photo'. Also, be sure to include the alt attribute on your img elements to ensure that a wider variety of users have access to that information.

From here you are in a great place to explore what Bootstrap has to offer. Here's some more info on how to create a flashier navigation bar by including Bootstrap in your project - https://v4-alpha.getbootstrap.com/components/navbar/

Have fun and keep up the good work!

**Comment by jane548** [comment]
Thanks for reviewing my code Francis! I appreciate the input. I styled that one location div differently to change the opacity (using rgba).

Cheers, -A
